name: BeerMap Backend CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: beermap
          POSTGRES_USER: beermap
          POSTGRES_PASSWORD: beermap
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    defaults:
      run:
        working-directory: api

    env:
      DATABASE_URL: postgresql+psycopg2://beermap:beermap@localhost:5432/beermap
      REDIS_URL: redis://localhost:6379/0
      JWT_SECRET: supersecret_ci

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests
        run: pytest -v